PRIMARY_COLOR = "#2A629A"
PRIMARY_COLOR2 = "#235586"
SECONDARY_COLOR = "#EA7712"
SECONDARY_COLOR2 = "#C9650D"

CONTENT_COLOR = "#D9D9D9"
CONTENT_COLOR2 = "#C4C4C4"
SIDEMENU_COLOR = "#2A629A"

BTN_BACKGROUND_COLOR = "#2A629A"
BTN_TEXT_COLOR = "#EFEFEF"
BTN_HOVER_BACKGROUND_COLOR = "#D36F17"
BTN_HOVER_TEXT_COLOR = "#EFEFEF"

# Widgets
LINE_EDIT_BACKGROUND_COLOR = "#EFEFEF"
GROUP_BOX_BACKGROUND_COLOR = "#E2E2E2"

TEXT_COLOR = "#747474"

ICON_COLOR = "#EFEFEF"
ICON_HOVER_COLOR = "#EFEFEF"