PRIMARY_COLOR = "#0D6EFD"
PRIMARY_COLOR2 = "#0D5BD1"
SECONDARY_COLOR = "#EA7712"
SECONDARY_COLOR2 = "#C9650D"

CONTENT_COLOR = "#DFDFDF"
CONTENT_COLOR2 = "#DFDFDF"
SIDEMENU_COLOR = "#2A629A"

BTN_BACKGROUND_COLOR = "#2A629A"
BTN_TEXT_COLOR = "#EFEFEF"
BTN_HOVER_BACKGROUND_COLOR = "#D36F17"
BTN_HOVER_TEXT_COLOR = "#EFEFEF"

# Widgets
LINE_EDIT_BACKGROUND_COLOR = "#EFEFEF"
GROUP_BOX_BACKGROUND_COLOR = "#E2E2E2"

BACKGROUND_COLOR = "#F3F3F3"
SHADOW_BACKGROUND_COLOR = "#D1D1D1"

TEXT_COLOR = "#505050"
SUBTITLE_COLOR = "#8B8B8B"

ICON_COLOR = "#F3F3F3"
ICON_HOVER_COLOR = "#F3F3F3"