PRIMARY_COLOR = "#2A629A"
SECONDARY_COLOR = "#EA7712"

CONTENT_COLOR = "#D9D9D9"
SIDEMENU_COLOR = "#2A629A"

BTN_BACKGROUND_COLOR = "#2A629A"
BTN_TEXT_COLOR = "#EFEFEF"
BTN_HOVER_BACKGROUND_COLOR = "#D36F17"
BTN_HOVER_TEXT_COLOR = "#EFEFEF"

LINE_BACKGROUND_COLOR = "#EFEFEF"

TEXT_COLOR = "#747474"

ICON_COLOR = "#EFEFEF"
ICON_HOVER_COLOR = "#EFEFEF"